### ISSUE TITLE
can you provide demo code for android..?

### ISSUE THREAD

**Issue by iiitmahesh** [ak1394/react-native-login#1]
can you provide demo code for android..?

**Comment by ak1394** [comment]
Do you mean the app code? https://github.com/ak1394/react-native-login-example

**Comment by iiitmahesh** [comment]
@ak1394 I'm not able to understand and use these redirect_uri, appsite_uri. always redirecting to redirect_url

**Comment by ak1394** [comment]
Did you read the article? https://medium.com/@ak1394/simple-social-login-for-react-native-apps-71279bf80ffc

All relevant code is on the github and setup is described in the article. Some of it might be a bit outdated, with regards to react native versions and such, but I'm not going to update it and can't provide much support besides this.

**Comment by iiitmahesh** [comment]
I followed the article, it was not working for android for me. Am I missing any step,  something like RCTLinking.xcodeproj??  is there any thing similar to this in andorid Should I use any intents for android version??

> However, once a user has authenticated we have to return to the app. Re-launching the app is done using iOS Universal Link, therefore the React Native Linking module needs to be properly configured.

How to do this android???
